name: "miniprogram-ci-action"
description: "使用 miniprogram-ci 预览和上传微信小程序的 GitHub Action。"
author: "gexin1"
branding:
  icon: package
  color: green
inputs:
  action_type:
    description: "执行类型，可选 preview 或 upload"
    required: false
    default: upload
  project_path:
    description: "小程序项目路径，需要包含 project.config.json"
    required: false
    default: "."
  page_path:
    description: "预览页面路径，需要是 app.json 中声明的页面"
    required: false
  page_query:
    description: "预览页面启动参数"
    required: false
    default: ""
  scene:
    description: "预览场景值"
    required: false
    default: "1011"
  version:
    description: "上传版本号"
    required: false
    default: 1.0.0
  description:
    description: "上传备注"
    required: false
  ci:
    description: "CI 机器人编号，取值范围 1-30"
    required: false
    default: "24"
outputs:
  preview_qrcode:
    description: "小程序预览二维码的 base64 内容"
  preview_qrcode_path:
    description: "小程序预览二维码的本地文件路径"
runs:
  using: "node24"
  pre: "./scripts/install.ts"
  main: "./src/index.ts"
